In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3,90])
print(type(a))

<class 'numpy.ndarray'>


In [3]:
print(a.shape)
print(a[0], a[1], a[2])
a[0] = 5
print(a)

(4,)
1 2 3
[ 5  2  3 90]


In [4]:
a_row = np.array([[1, 2, 3]])
print(a_row.shape)

(1, 3)


In [5]:
a_col = np.array([[1], [2], [3]])
print(a_col.shape)

(3, 1)


In [7]:
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


In [8]:
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [9]:
b = np.ones((1,2))
print(b)

[[1. 1.]]


In [10]:
c = np.full((2,2), 7)
print(c)

[[7 7]
 [7 7]]


In [11]:
d = np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [15]:
e = np.random.rand((2,2))
print(e)

[[0.27745147 0.6675667 ]
 [0.62478074 0.0788272 ]]


In [16]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [17]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
row_r2 = a[1:2, :]
print(row_r2, row_r2.shape)

[[5 6 7 8]] (1, 4)


In [23]:
col_r1 = a[:, 1] #indexing
col_r2 = a[:, 1:2] # slicing
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [24]:
#so it means that indexing reduces the dimension while
#slicing preserves the dimension .
# we will mostly use slicing to avoid the broadcasting errors

In [25]:
x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)
x

int64


array([1, 2])

In [26]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [27]:
print(x + y)

[[ 6.  8.]
 [10. 12.]]


In [28]:
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]


In [29]:
print(x - y)

[[-4. -4.]
 [-4. -4.]]


In [31]:
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]


In [32]:
print(x * y)

[[ 5. 12.]
 [21. 32.]]


In [33]:
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]


In [34]:
print(x / y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [35]:
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [36]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [28]:
a = np.array([1, 2, 3, 4, 5, 6])
print("Original:", a)
print("Shape:", a.shape)

Original: [1 2 3 4 5 6]
Shape: (6,)


In [29]:
b = a.reshape(2, 3)   # 2 rows, 3 columns
print(b)
print("Shape:", b.shape)

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


In [30]:
c = a.reshape(3, 2)
print(c)
print("Shape:", c.shape)

[[1 2]
 [3 4]
 [5 6]]
Shape: (3, 2)


In [31]:
d = a.reshape(1, 6)
print(d)
print("Shape:", d.shape)

[[1 2 3 4 5 6]]
Shape: (1, 6)


In [32]:
e = a.reshape(6, 1)
print(e)
print("Shape:", e.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
Shape: (6, 1)


In [33]:
f = a.reshape(2, -1)  # -1 means "whatever fits"
print(f)
print("Shape:", f.shape)

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


In [ ]:
# Exercise

### Exercise Solutions

In [39]:


# --- resize vs reshape ---
print("--- resize vs reshape ---")
arr = np.array([1, 2, 3, 4, 5, 6])
print("Original array for resize/reshape:", arr)

# Example 1: reshape - creates a new view, original array unchanged
reshaped_arr = arr.reshape(2, 3)
print("Reshaped array (2x3):\n", reshaped_arr)
print("Original array after reshape (unchanged):", arr)

# Example 2: resize - changes the array in-place, can pad or truncate
arr_resize = np.array([1, 2, 3, 4])
arr_resize.resize((3, 3)) # Resize to a larger size, pads with zeros
print("\nArray after resize to (3,3) (padded):\n", arr_resize)

arr_resize_2 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr_resize_2.resize((2, 3)) # Resize to a smaller size, truncates
print("Array after resize to (2,3) (truncated):\n", arr_resize_2)

--- resize vs reshape ---
Original array for resize/reshape: [1 2 3 4 5 6]
Reshaped array (2x3):
 [[1 2 3]
 [4 5 6]]
Original array after reshape (unchanged): [1 2 3 4 5 6]

Array after resize to (3,3) (padded):
 [[1 2 3]
 [4 0 0]
 [0 0 0]]
Array after resize to (2,3) (truncated):
 [[1 2 3]
 [4 5 6]]


### Remaining Exercise Solutions

In [43]:


# --- sort ---
print("\n--- sort ---")
arr_sort = np.array([[3, 1, 2], [6, 5, 4]])
print("Original array for sort:\n", arr_sort)
print("Sorted along last axis (default):\n", np.sort(arr_sort))
print("Sorted along axis 0:\n", np.sort(arr_sort, axis=0))



--- sort ---
Original array for sort:
 [[3 1 2]
 [6 5 4]]
Sorted along last axis (default):
 [[1 2 3]
 [4 5 6]]
Sorted along axis 0:
 [[3 1 2]
 [6 5 4]]


In [44]:


# --- argsort ---
print("\n--- argsort ---")
arr_argsort = np.array([[3, 1, 2], [6, 5, 4]])
print("Original array for argsort:\n", arr_argsort)
print("Indices that would sort along last axis:\n", np.argsort(arr_argsort))
print("Indices that would sort along axis 0:\n", np.argsort(arr_argsort, axis=0))



--- argsort ---
Original array for argsort:
 [[3 1 2]
 [6 5 4]]
Indices that would sort along last axis:
 [[1 2 0]
 [2 1 0]]
Indices that would sort along axis 0:
 [[0 0 0]
 [1 1 1]]


In [45]:


# --- unique ---
print("\n--- unique ---")
arr_unique = np.array([1, 2, 2, 3, 3, 3, 4, 1])
print("Original array for unique:", arr_unique)
print("Unique elements:", np.unique(arr_unique))
print("Unique elements and their counts:", np.unique(arr_unique, return_counts=True))



--- unique ---
Original array for unique: [1 2 2 3 3 3 4 1]
Unique elements: [1 2 3 4]
Unique elements and their counts: (array([1, 2, 3, 4]), array([2, 2, 3, 1]))


In [46]:


# --- where ---
print("\n--- where ---")
arr_where = np.array([[1, 2, 3], [4, 5, 6]])
print("Original array for where:\n", arr_where)
print("Indices where elements are greater than 3:", np.where(arr_where > 3))
print("Conditional replacement (even/odd):\n", np.where(arr_where % 2 == 0, 'even', 'odd'))



--- where ---
Original array for where:
 [[1 2 3]
 [4 5 6]]
Indices where elements are greater than 3: (array([1, 1, 1]), array([0, 1, 2]))
Conditional replacement (even/odd):
 [['odd' 'even' 'odd']
 ['even' 'odd' 'even']]


In [47]:


# --- nonzero ---
print("\n--- nonzero ---")
arr_nonzero = np.array([0, 1, 2, 0, 3, 0, 4])
print("Original array for nonzero:", arr_nonzero)
print("Indices of non-zero elements:", np.nonzero(arr_nonzero))
print("Indices where elements are greater than 1:", np.nonzero(arr_nonzero > 1))



--- nonzero ---
Original array for nonzero: [0 1 2 0 3 0 4]
Indices of non-zero elements: (array([1, 2, 4, 6]),)
Indices where elements are greater than 1: (array([2, 4, 6]),)


In [48]:


# --- min, max, mean, median, std, var, sum, prod ---
print("\n--- Min, Max, Mean, Median, Std, Var, Sum, Prod ---")
arr_stats = np.array([[1, 2, 3], [4, 5, 6]])
print("Original array for stats:\n", arr_stats)
print("Min, Max:", arr_stats.min(), arr_stats.max())
print("Mean, Median:", arr_stats.mean(), np.median(arr_stats))
print("Standard Deviation, Variance:", arr_stats.std(), arr_stats.var())
print("Sum, Product:", arr_stats.sum(), arr_stats.prod())



--- Min, Max, Mean, Median, Std, Var, Sum, Prod ---
Original array for stats:
 [[1 2 3]
 [4 5 6]]
Min, Max: 1 6
Mean, Median: 3.5 3.5
Standard Deviation, Variance: 1.707825127659933 2.9166666666666665
Sum, Product: 21 720


In [49]:


# --- argmin, argmax ---
print("\n--- Argmin, Argmax ---")
arr_argminmax = np.array([[1, 2, 3], [6, 5, 4]])
print("Original array for argmin/argmax:\n", arr_argminmax)
print("Index of minimum element (flattened):", arr_argminmax.argmin())
print("Index of maximum element (flattened):", arr_argminmax.argmax())
print("Argmin along axis 0:", arr_argminmax.argmin(axis=0))
print("Argmax along axis 1:", arr_argminmax.argmax(axis=1))



--- Argmin, Argmax ---
Original array for argmin/argmax:
 [[1 2 3]
 [6 5 4]]
Index of minimum element (flattened): 0
Index of maximum element (flattened): 3
Argmin along axis 0: [0 0 0]
Argmax along axis 1: [2 0]


In [50]:


# --- random.rand(), random.randn(), random.randint() ---
print("\n--- Random examples ---")
print("3 random floats in [0.0, 1.0):", np.random.rand(3))
print("3 random floats from standard normal distribution:", np.random.randn(3))
print("3 random integers in [1, 10):", np.random.randint(1, 10, 3))



--- Random examples ---
3 random floats in [0.0, 1.0): [0.70065169 0.48715812 0.52042451]
3 random floats from standard normal distribution: [ 1.69262046  1.20338711 -0.58000888]
3 random integers in [1, 10): [8 1 1]


In [56]:


# --- linalg.inv() ---
print("\n--- linalg.inv() ---")
a_inv = np.array([[1,2],[3,4]])
print("Original matrix:\n", a_inv)
inverse_a = np.linalg.inv(a_inv)
print("Inverse of matrix:\n", inverse_a)

b_inv = np.array([[4,7],[2,6]])
print("\nOriginal matrix:\n", b_inv)
inverse_b = np.linalg.inv(b_inv)
print("Inverse of matrix:\n", inverse_b)



--- linalg.inv() ---
Original matrix:
 [[1 2]
 [3 4]]
Inverse of matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]

Original matrix:
 [[4 7]
 [2 6]]
Inverse of matrix:
 [[ 0.6 -0.7]
 [-0.2  0.4]]


In [57]:


# --- linalg.det() ---
print("\n--- linalg.det() ---")
a_det = np.array([[1,2],[3,4]])
print("Original matrix:\n", a_det)
determinant_a = np.linalg.det(a_det)
print("Determinant of matrix:\n", determinant_a)

b_det = np.array([[4,7],[2,6]])
print("\nOriginal matrix:\n", b_det)
determinant_b = np.linalg.det(b_det)
print("Determinant of matrix:\n", determinant_b)



--- linalg.det() ---
Original matrix:
 [[1 2]
 [3 4]]
Determinant of matrix:
 -2.0000000000000004

Original matrix:
 [[4 7]
 [2 6]]
Determinant of matrix:
 10.000000000000002


In [58]:


# --- linalg.eig() ---
print("\n--- linalg.eig() ---")
a_eig = np.array([[2, 0],[0, 3]])
print("Original matrix:\n", a_eig)
e_vals, e_vecs = np.linalg.eig(a_eig)
print("Eigenvalues:\n", e_vals)
print("Eigenvectors:\n", e_vecs)

b_eig = np.array([[1, 2],[3, 4]])
print("\nOriginal matrix:\n", b_eig)
e_vals_b, e_vecs_b = np.linalg.eig(b_eig)
print("Eigenvalues:\n", e_vals_b)
print("Eigenvectors:\n", e_vecs_b)



--- linalg.eig() ---
Original matrix:
 [[2 0]
 [0 3]]
Eigenvalues:
 [2. 3.]
Eigenvectors:
 [[1. 0.]
 [0. 1.]]

Original matrix:
 [[1 2]
 [3 4]]
Eigenvalues:
 [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [59]:

# --- linalg.svd() ---
print("\n--- linalg.svd() ---")
a_svd = np.array([[1, 1], [1, 0], [0, 1]])
print("Original matrix:\n", a_svd)
U, s, Vh = np.linalg.svd(a_svd)
print("U matrix:\n", U)
print("Singular values (s):\n", s)
print("V transpose (Vh) matrix:\n", Vh)

b_svd = np.array([[1, 2, 3], [4, 5, 6]])
print("\nOriginal matrix:\n", b_svd)
U_b, s_b, Vh_b = np.linalg.svd(b_svd)
print("U matrix:\n", U_b)
print("Singular values (s):\n", s_b)
print("V transpose (Vh) matrix:\n", Vh_b)



--- linalg.svd() ---
Original matrix:
 [[1 1]
 [1 0]
 [0 1]]
U matrix:
 [[-8.16496581e-01  1.85577521e-16 -5.77350269e-01]
 [-4.08248290e-01 -7.07106781e-01  5.77350269e-01]
 [-4.08248290e-01  7.07106781e-01  5.77350269e-01]]
Singular values (s):
 [1.73205081 1.        ]
V transpose (Vh) matrix:
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

Original matrix:
 [[1 2 3]
 [4 5 6]]
U matrix:
 [[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]
Singular values (s):
 [9.508032   0.77286964]
V transpose (Vh) matrix:
 [[-0.42866713 -0.56630692 -0.7039467 ]
 [ 0.80596391  0.11238241 -0.58119908]
 [ 0.40824829 -0.81649658  0.40824829]]


In [60]:


# --- linalg.norm() ---
print("\n--- linalg.norm() ---")
a_norm = np.array([[1, -2], [3, -4]])
print("Original matrix:\n", a_norm)
print("Frobenius norm:\n", np.linalg.norm(a_norm))
print("1-norm (maximum column sum):\n", np.linalg.norm(a_norm, ord=1))

v_norm = np.array([1,2,3])
print("\nOriginal vector:\n", v_norm)
print("L2 norm (Euclidean norm):\n", np.linalg.norm(v_norm))
print("L1 norm:\n", np.linalg.norm(v_norm, ord=1))



--- linalg.norm() ---
Original matrix:
 [[ 1 -2]
 [ 3 -4]]
Frobenius norm:
 5.477225575051661
1-norm (maximum column sum):
 6.0

Original vector:
 [1 2 3]
L2 norm (Euclidean norm):
 3.7416573867739413
L1 norm:
 6.0


In [51]:


# --- ndim ---
print("\n--- Number of dimensions (ndim) ---")
arr_1d_ndim = np.array([1, 2, 3])
arr_2d_ndim = np.array([[1, 2], [3, 4]])
arr_3d_ndim = np.array([[[1, 2]]])
print("Dimensions of 1D array:", arr_1d_ndim.ndim)
print("Dimensions of 2D array:\n", arr_2d_ndim.ndim)
print("Dimensions of 3D array:\n", arr_3d_ndim.ndim)



--- Number of dimensions (ndim) ---
Dimensions of 1D array: 1
Dimensions of 2D array:
 2
Dimensions of 3D array:
 3


In [52]:


# --- expand_dims ---
print("\n--- expand_dims ---")
arr_expand = np.array([1, 2, 3])
print("Original array for expand_dims:", arr_expand, "Shape:", arr_expand.shape)
print("Expanded at axis 0:\n", np.expand_dims(arr_expand, axis=0), "Shape:", np.expand_dims(arr_expand, axis=0).shape)
print("Expanded at axis 1:\n", np.expand_dims(arr_expand, axis=1), "Shape:", np.expand_dims(arr_expand, axis=1).shape)



--- expand_dims ---
Original array for expand_dims: [1 2 3] Shape: (3,)
Expanded at axis 0:
 [[1 2 3]] Shape: (1, 3)
Expanded at axis 1:
 [[1]
 [2]
 [3]] Shape: (3, 1)


In [53]:


# --- swapaxes ---
print("\n--- swapaxes ---")
arr_swap = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
print("Original 3D array for swapaxes (shape {0}):\n{1}".format(arr_swap.shape, arr_swap))
print("Swap axis 0 and 1 (shape {0}):\n{1}".format(np.swapaxes(arr_swap, 0, 1).shape, np.swapaxes(arr_swap, 0, 1)))
print("Swap axis 0 and 2 (shape {0}):\n{1}".format(np.swapaxes(arr_swap, 0, 2).shape, np.swapaxes(arr_swap, 0, 2)))



--- swapaxes ---
Original 3D array for swapaxes (shape (2, 2, 2)):
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
Swap axis 0 and 1 (shape (2, 2, 2)):
[[[0 1]
  [4 5]]

 [[2 3]
  [6 7]]]
Swap axis 0 and 2 (shape (2, 2, 2)):
[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]


In [54]:


# --- Basic indexing ---
print("\n--- Basic indexing ---")
arr_basic_idx_a = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]])
arr_basic_idx_b = np.array([[1,2,3],[4,5,6]])
print("Original array 'a':\n", arr_basic_idx_a)
print("Original array 'b':\n", arr_basic_idx_b)
print("First row of 'a':", arr_basic_idx_a[0])
print("Rows 1 to 2 (exclusive) of 'a':\n", arr_basic_idx_a[1:3])
print("Element at (row 0, col 2) of 'b':", arr_basic_idx_b[0, 2])
print("Second row of 'b':", arr_basic_idx_b[1,:])



--- Basic indexing ---
Original array 'a':
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
Original array 'b':
 [[1 2 3]
 [4 5 6]]
First row of 'a': [10 20 30 40]
Rows 1 to 2 (exclusive) of 'a':
 [[ 50  60  70  80]
 [ 90 100 110 120]]
Element at (row 0, col 2) of 'b': 3
Second row of 'b': [4 5 6]


In [55]:


# --- Boolean indexing ---
print("\n--- Boolean indexing ---")
arr_bool_idx_a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_bool_idx_b = np.array([[10, 11, 12], [13, 14, 15]])
print("Original array 'a':\n", arr_bool_idx_a)
print("Original array 'b':\n", arr_bool_idx_b)
print("Elements of 'a' greater than 3:", arr_bool_idx_a[arr_bool_idx_a > 3])
print("Elements of 'b' that are even:", arr_bool_idx_b[arr_bool_idx_b % 2 == 0])



--- Boolean indexing ---
Original array 'a':
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Original array 'b':
 [[10 11 12]
 [13 14 15]]
Elements of 'a' greater than 3: [4 5 6 7 8 9]
Elements of 'b' that are even: [10 12 14]


In [40]:
# --- squeeze ---
print("\n--- squeeze ---")

# Example 1: Remove single-dimensional entries (axes of length 1)
a = np.array([[[0], [1], [2]]])
print("Original array for squeeze:\n", a, "\nShape:", a.shape)
squeezed_a = np.squeeze(a)
print("Squeezed array:\n", squeezed_a, "\nShape:", squeezed_a.shape)

# Example 2: Squeeze a 1D array (no effect)
b = np.array([1, 2, 3])
print("\nOriginal 1D array for squeeze:", b, "\nShape:", b.shape)
squeezed_b = np.squeeze(b)
print("Squeezed 1D array:", squeezed_b, "\nShape:", squeezed_b.shape)


--- squeeze ---
Original array for squeeze:
 [[[0]
  [1]
  [2]]] 
Shape: (1, 3, 1)
Squeezed array:
 [0 1 2] 
Shape: (3,)

Original 1D array for squeeze: [1 2 3] 
Shape: (3,)
Squeezed 1D array: [1 2 3] 
Shape: (3,)


In [41]:
# --- flatten ---
print("\n--- flatten ---")

# Example 1: Flatten a 2D array to 1D (default 'C' order)
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Original matrix for flatten:\n", matrix)
flattened_c = matrix.flatten()
print("Flattened (C-order):", flattened_c)

# Example 2: Flatten a 2D array to 1D (Fortran-like 'F' order)
flattened_f = matrix.flatten(order='F')
print("Flattened (F-order):", flattened_f)


--- flatten ---
Original matrix for flatten:
 [[1 2 3]
 [4 5 6]]
Flattened (C-order): [1 2 3 4 5 6]
Flattened (F-order): [1 4 2 5 3 6]


In [42]:
# --- ravel ---
print("\n--- ravel ---")

# Example 1: Ravel a 2D array to 1D (default 'C' order - similar to flatten)
matrix_ravel = np.array([[1, 2, 3], [4, 5, 6]])
print("Original matrix for ravel:\n", matrix_ravel)
raveled_c = matrix_ravel.ravel()
print("Raveled (C-order):", raveled_c)

# Example 2: Ravel a 2D array to 1D (Fortran-like 'F' order)
raveled_f = matrix_ravel.ravel(order='F')
print("Raveled (F-order):", raveled_f)

# Note: ravel returns a view when possible, flatten always returns a copy.


--- ravel ---
Original matrix for ravel:
 [[1 2 3]
 [4 5 6]]
Raveled (C-order): [1 2 3 4 5 6]
Raveled (F-order): [1 4 2 5 3 6]


In [ ]:
# 2 example each
# resize ( vs reshape)
# squeeze
# flatten
# ravel
# sort
# argsort
# unique
# where
# nonzero
# min
# max
# mean
# median
# std
# var
# sum
# prod
# argmin
# argmax
# random.rand()
# random.randn()
# random.randint()
# ndim
# expand_dims
# swapaxes
# Basic indexing (a[0], a[1:3])
# Boolean indexing (a[a > 5])
# linalg.inv()
# linalg.det()
# linalg.eig()
# linalg.svd()
# linalg.norm()